/:
  controller: Base
  action: Default

/tableau-de-bord:
  controller: Base
  action: dashboard


/s-inscrire:
  controller: Security
  action: register

/login:
  controller: Security
  action: login

/se-connecter:
  controller: Security
  action: login


/logout:
  controller: Security
  action: logout


/liste-des-utilisateurs:
  controller: Security
  action: listofusers

/articles:
  controller: Base
  action: articles

/articles-add:
  controller: Security
  action: addArticle

/articles-edit:
  controller: Base
  action: editArticle

/display-articles:
  controller: Base
  action: displayArticle