/:
  controller: Base
  action: dashboard

/tableau-de-bord:
  controller: Base
  action: dashboard

/s-inscrire:
  controller: Security
  action: register

/confirmation:
  controller: Security
  action: confirmation

/login:
  controller: Security
  action: login

/mot-de-passe-oublie:
  controller : Security
  action : recuperation

/changement-mdp:
  controller: Security
  action: changementmdp
  
/logout:
  controller: Security
  action: logout


/liste-des-utilisateurs:
  controller: Security
  action: listofusers

/articles:
  controller: Base
  action: articles

/articles-add:
  controller: Base
  action: addArticle

/articles-edit:
  controller: Base
  action: editArticle
  
/utilisateurs:
  controller: Base
  action: users

/pages:
  controller: Base
  action: pages

/apparence:
  controller: Base
  action: apparence

/profil:
  controller: Base
  action: profile
  
/FAQ:
  controller: Base
  action: FAQ

/categories:
  controller: Base
  action: categories

/edit-categorie:
  controller: Base
  action: editCategorie